name: Deploy to EKS (HTTPS)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

     
      - name: uveshkhan
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest .

      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest

      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name my-cluster --region ap-southeast-2

      
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/wisecow-deployment wisecow=${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest --record

     
      - name: Apply Service and Ingress
        run: |
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress-https.yaml
