name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Run when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            uveshkhan/accuknox:latest
            uveshkhan/accuknox:${{ github.sha }}

      # (Optional) Step 4: Deploy to Kubernetes
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.0   # choose your cluster version

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deploysvc.yml
