name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Runs on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t uveshkhan/accuknox:v5 .
        docker tag uveshkhan/accuknox:v5 uveshkhan/accuknox:latest

    - name: Push Docker Image
      run: |
        docker push uveshkhan/accuknox:v5
        docker push uveshkhan/accuknox:latest

    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v3
      with:
        version: v1.31.0  # Your cluster version

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/deploysvc.yml
